export const ADD_SERVICE = 'ADD_SERVICE';
export const GET_SERVICE = 'GET_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const MODAL_SERVICE = 'MODAL_SERVICE';